name: aaradhana_downloader
description: A VIP YouTube Audio/Video Downloader for RajuBhai.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
